title: 'name'
description: 'description'
modified: 'oModified'
origin: # only keep the id and recipe name if id is available
    id: '?' # system ID that represents origin (type, author, source, reference)
    authors: # will disregard content if id is present
        REGEX: '?'
        id: '?'
        name: '?'
        reference: '?'
    source: 'oSource'
    reference: 'oLocation' #the link to the source ()
    type:
        VALUES: ['PUBLICATION', 'WEBSITE', 'PERSON']
    recipe: 'oName'
categories:
    REGEX: '?'
images:
    REGEX: '?'

equipment: # will disregard content if id is present
    REGEX: '?'
    id: '?'
    name: '?'
    quantity: '?'
ingredients: # if id is available, will disregard information
    REGEX: '?'
    id: '?'
    name: 'ingredient{}'
    preperation: 'prep{}' # the way the ingredient is prepared (Sifted, Sliced, Diced, Melted, etc.)
    amount: 'amount{}' # quantity in grams, see documentation on calculations
    bakers_percent:
        base: 'bp_base{}'
        percent: 'bp_amount{}'

preperation:
    ordered: '?'
    notes:
        REGEX: '?'
        comment: '?'
        ingredients: '?'
serving: '' #duplication of preperation
storage: '' #duplication of preperation
tips: '' #duplication of preperation

times:
    REGEX: '?'
nutrition: 'HELP ME'
portions:
    minimum: '?' # for items like pie where single portions are generally not feasible
    yield: '?'
    description: '?'
yield: '?'
